name: footballAPP

on:
  push:

    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install curl

      run: sudo apt update && sudo apt install -y pip && pip install pytest

    - name: Build docker
      run: docker build -t footballanalysis .

    - name: Run docker
      run: docker run -d -p 8080:5000 footballanalysis

    - name: Wait for docker to start
      run: sleep 10

    - name: Test connection to docker
      run: curl http://127.0.0.1:8080

    - name: Set release tag
      if: github.event_name == 'release'
      run: |
        DOCKER_TAG="footballanalysis.${{ github.event.release.tag_name }}"
        docker tag footballanalysis "${DOCKER_TAG}"
        echo "${{secrets.DOCKERPASSWORD}}" | docker login -u miiruki --password-stdin
        docker push "${DOCKER_TAG}"
