name: footballAPP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install curl
      run: sudo apt update && sudo apt install -y curl

    - name: Build docker
      run: docker build -t footballanalysis .

    - name: Run docker
      run: docker run -d -p 8080:5000 footballanalysis

    - name: Wait for docker to start
      run: sleep 10

    - name: Test connection to docker
      run: curl http://127.0.0.1:8080

    - name: Connect to dockerhub
      run: echo "${{secrets.DOCKERPASSWORD}}" | docker login -u miiruki --password-stdin

    - name: Upload image to dockerhub
      run: docker tag footballanalysis "miiruki/footballanalysis" && docker push "miiruki/footballanalysis"
