name: footballAPP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install curl
      run: sudo apt update && sudo apt install -y curl

    - name: Build docker
      run: docker build -t fotballapp .

    - name: Run docker
      run: docker run -d -p 8080:5000 fotballapp

    - name: Wait for docker to start
      run: sleep 10

    - name: Test connection to docker
      run: curl http://127.0.0.1:8080

    # - name: Connect to dockerhub
    #   run: echo "$DOCKERPASSWORD" | docker login -u miiruki --password-stdin

    # - name: Upload image to dockerhub
    #   run: docker tag fa_nodejs_sample "miiruki/fa_nodejs_sample" && docker push "miiruki/fa_nodejs_sample"
